name: Java CI

on: [push]

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: status gradle
        working-directory: ./quarkus-app
        run: ./gradlew --status
      
      - name: clean gradle
        working-directory: ./quarkus-app
        run: ./gradlew --stop

      - name: build gradle
        working-directory: ./quarkus-app
        run: ./gradlew clean build --parallel --max-workers=4